### ISSUE TITLE
Wire Frame 만들기

### ISSUE THREAD

**Issue by newkidsean** [newkidsean/blog-with-nextjs#3]
**TO-DO**

- [x] Main page 만들기
- [x] Post page 만들기
- [x] About page 만들기
- [x] My page 만들기
